version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: standard
      - dependency-name: ts-standard
      - dependency-name: "@types/node"
      - dependency-name: voxpelli/tsconfig
      - dependency-name: typescript
      - dependency-name: hallmark
      - dependency-name: "@babel/preset-env"
      - dependency-name: babelify

      # Stay on the 3rd or 4th oldest stable release, per
      # https://www.electronjs.org/docs/latest/tutorial/electron-timelines#version-support-policy
      - dependency-name: electron
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
