providers:
  - airtap-playwright

browsers:
  - name: chromium
  - name: firefox
  - name: webkit

presets:
  electron:
    providers:
      - airtap-electron
    browsers:
      - name: electron

# Until airtap switches to rollup
browserify:
  - transform: babelify
    presets: ["@babel/preset-env"]
