name: Browsers
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    name: Test
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: npm install --ignore-scripts
      - name: Install Playwright dependencies
        run: npx --no-install playwright install-deps
      - name: Install Playwright
        run: npx --no-install playwright install
      - name: Test
        run: npm run test-browsers
