name: Test
on: [push, pull_request]
jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20]
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install --ignore-scripts
      - name: Test
        run: npm test
      - name: Coverage
        run: npm run coverage
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
  browsers:
    name: Browsers
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install
        run: npm install --ignore-scripts
      - name: Install Playwright dependencies
        run: npx --no-install playwright install-deps
      - name: Install Playwright
        run: npx --no-install playwright install
      - name: Test
        run: npm run test-browsers
  electron:
    name: Electron
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install
        run: npm install --ignore-scripts
      - name: Install Electron
        run: npm run postinstall
        working-directory: node_modules/electron
      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test-electron
